version: "3.9"

services:
  db:
    image: mysql:8.1
    container_name: netsol-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: namesdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306" # optional for local access
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    container_name: netsol-backend
    environment:
      - MY_NAME=Ahmad
      - DB_HOST=db
      - DB_USER=appuser
      - DB_PASSWORD=apppass
      - DB_NAME=namesdb
    ports:
      - "3000:3000" # access backend locally
    volumes:
      - ./backend:/app           # mount source code for live reload
      - /app/node_modules        # prevent overwriting container node_modules
    depends_on:
      - db
    command: npm run dev         # run nodemon for hot reload
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    container_name: netsol-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html        # live updates for HTML/CSS/JS
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf  # optional Nginx config live mount
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  db_data:
